from enum import Enum


class UserRole(str, Enum):
    USER = 'USER'
    STAFF = 'STAFF'
    LOCAL_ADMIN = 'LOCAL_ADMIN'
    GATEWAY_ADMIN = 'GATEWAY_ADMIN'
    SERVER_ADMIN = 'SERVER_ADMIN'


class ParcelStatus(str, Enum):
    CREATED = 'CREATED'
    PRE_REGISTERED = 'PRE_REGISTERED'
    ARRIVED_AT_STATION = 'ARRIVED_AT_STATION'
    STORED = 'STORED'
    WAITING_PICKUP = 'WAITING_PICKUP'
    FINDING = 'FINDING'
    PICKUP_VERIFYING = 'PICKUP_VERIFYING'
    PICKED_UP = 'PICKED_UP'
    EXCEPTION = 'EXCEPTION'
    CANCELLED = 'CANCELLED'


class ParcelOrigin(str, Enum):
    EXPRESS_COMPANY = 'EXPRESS_COMPANY'
    SERVER_MANUAL = 'SERVER_MANUAL'
    GATEWAY_INBOUND = 'GATEWAY_INBOUND'
    GATEWAY_CORRECTION = 'GATEWAY_CORRECTION'


class ParcelSyncStatus(str, Enum):
    SERVER_ONLY = 'SERVER_ONLY'
    LOCAL_ONLY = 'LOCAL_ONLY'
    SYNC_PENDING = 'SYNC_PENDING'
    SYNCED = 'SYNCED'
    MERGED = 'MERGED'
    CONFLICT = 'CONFLICT'


class TagStatus(str, Enum):
    IDLE = 'IDLE'
    ONLINE = 'ONLINE'
    OFFLINE = 'OFFLINE'
    RUNNING = 'RUNNING'
    LOW_BATTERY = 'LOW_BATTERY'
    ERROR = 'ERROR'
    TAMPER = 'TAMPER'
    DISABLED = 'DISABLED'


class ParcelTagBindingStatus(str, Enum):
    ACTIVE = 'ACTIVE'
    RELEASED = 'RELEASED'
    CANCELLED = 'CANCELLED'


class PickupEventType(str, Enum):
    NOTIFIED = 'NOTIFIED'
    NFC_ACCESS = 'NFC_ACCESS'
    TAG_WAKE = 'TAG_WAKE'
    PICKUP_CONFIRMED = 'PICKUP_CONFIRMED'
    PICKUP_SYNCED = 'PICKUP_SYNCED'
    OFFLINE_PICKUP = 'OFFLINE_PICKUP'


class EventSource(str, Enum):
    SERVER = 'SERVER'
    GATEWAY = 'GATEWAY'
    MINIPROGRAM = 'MINIPROGRAM'


class SyncDirection(str, Enum):
    GATEWAY_TO_SERVER = 'GATEWAY_TO_SERVER'
    SERVER_TO_GATEWAY = 'SERVER_TO_GATEWAY'


class SyncStatus(str, Enum):
    PENDING = 'PENDING'
    SENT = 'SENT'
    ACKED = 'ACKED'
    FAILED = 'FAILED'


class GatewayRegistrationTokenStatus(str, Enum):
    PENDING = 'PENDING'
    USED = 'USED'
    EXPIRED = 'EXPIRED'
    REVOKED = 'REVOKED'


class NotificationType(str, Enum):
    IN_APP = 'IN_APP'
    WECHAT_SUBSCRIBE = 'WECHAT_SUBSCRIBE'


class NotificationStatus(str, Enum):
    PENDING = 'PENDING'
    SENT = 'SENT'
    READ = 'READ'
    FAILED = 'FAILED'


class GatewayFactoryDeviceStatus(str, Enum):
    UNKNOWN_SEEN = 'UNKNOWN_SEEN'
    PENDING_BIND = 'PENDING_BIND'
    BOUND = 'BOUND'
    ONLINE = 'ONLINE'
    DISABLED = 'DISABLED'
    REVOKED = 'REVOKED'
