const CONFIG = require('../../services/config')
const gatewayApi = require('../../services/gateway-api')
const serverApi = require('../../services/server-api')
const { nowText } = require('../../utils/format')
Page({ data:{ gateway:{data:{}}, server:{data:{}}, mode:'mock mode', checkedAt:'', gatewayApi:CONFIG.gatewayBaseUrl }, onLoad(){ this.check() }, check(){ Promise.all([gatewayApi.getLocalHealth(), serverApi.getHealth()]).then(([g,s])=>{ const mode = g.source === 'real' ? 'gateway local available' : (s.source === 'real' ? 'server only' : 'mock mode'); this.setData({gateway:g, server:s, mode, checkedAt:nowText()}) }) } })
